package radio.ui.musiclibrary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import radio.ui.IApplicationWindow;
import radio.ui.MainController;
import radio.ui.MenuPanel;
import radio.ui.MusicLibraryController;

import javax.swing.*;
import java.awt.*;

public class MusicLibraryWindow implements IApplicationWindow {

    private JPanel background;
    private MenuPanel menuView;
    private SongListPanel songListPanel;

    private MainController controller;

    public MusicLibraryWindow(MainController controller) {
        this.controller = controller;
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        background = new JPanel();
        background.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        background.add(menuView.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, 1, null, null, null, 0, false));
        background.add(songListPanel.$$$getRootComponent$$$(), new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return background;
    }

    private void createUIComponents() {
        this.menuView = new MenuPanel(this.controller);
        this.songListPanel = new SongListPanel(new MusicLibraryController(this.controller));
        this.controller.addObserver(this.songListPanel);
    }

    @Override
    public JPanel getPanelHandler() {
        return (JPanel) $$$getRootComponent$$$();
    }

    @Override
    public void willShow() {
        this.menuView.willShow();
        this.songListPanel.willShow();
    }
}
