package radio.ui.adverts;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import radio.actions.ShowAdvertiserAds;
import radio.actions.ShowAdvertisers;
import radio.transfer.AdTransfer;
import radio.transfer.AdvertiserTransfer;
import radio.ui.*;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.stream.Collectors;

public class AdvertisingWindow implements IApplicationWindow, Observer {

    private JPanel panel1;
    private MenuPanel menuPanel;
    private JList advertiserList;
    private JButton showAdvertsButton;
    private JButton editButton;
    private JButton deleteButton;
    private JButton newButton;
    private JTextField searchField;
    private JButton addAdvertButtonButton;

    private MainController mainController;
    private AdvertsController controller;
    private DefaultListModel<String> listModel;
    private List<AdvertiserTransfer> advertiserData;

    public AdvertisingWindow(MainController controller) {
        this.mainController = controller;
        this.controller = new AdvertsController(controller);
        this.mainController.addObserver(this);

        $$$setupUI$$$();
        addAdvertButtonButton.addActionListener(_e -> onNewAd());
        showAdvertsButton.addActionListener(_e -> onShow());
    }

    // When user clicks on "add advert"
    private void onNewAd() {
        int idx = this.advertiserList.getSelectedIndex();
        if (idx == -1) {
            showSync("Select an advertiser on the left to create a new ad");
            return;
        }

        AdvertiserTransfer tr = this.advertiserData.get(idx);
        NewAdDialog dialog = new NewAdDialog(tr, this.controller);
        dialog.pack();
        dialog.willShow();
        dialog.setVisible(true);
    }

    // When user clicks on "show adverts"
    private void onShow() {
        int idx = this.advertiserList.getSelectedIndex();
        if (idx == -1) {
            showSync("Select an advertiser on the left to see its ads");
            return;
        }

        AdvertiserTransfer tr = this.advertiserData.get(idx);
        SwingUtilities.invokeLater(() -> this.controller.adsFor(tr));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.add(menuPanel.$$$getRootComponent$$$(), BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel2.add(scrollPane1, BorderLayout.CENTER);
        scrollPane1.setViewportView(advertiserList);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, BorderLayout.EAST);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.add(panel4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        showAdvertsButton = new JButton();
        showAdvertsButton.setText("Ver Anuncios");
        panel4.add(showAdvertsButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        editButton = new JButton();
        editButton.setText("Editar");
        panel4.add(editButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteButton = new JButton();
        deleteButton.setText("Eliminar");
        panel4.add(deleteButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addAdvertButtonButton = new JButton();
        addAdvertButtonButton.setText("Añadir Anuncio");
        panel4.add(addAdvertButtonButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel3.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel3.add(panel5, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        newButton = new JButton();
        newButton.setText("+");
        panel5.add(newButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel5.add(panel6, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Buscar");
        panel6.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        searchField = new JTextField();
        panel6.add(searchField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        this.menuPanel = new MenuPanel(mainController);
        this.listModel = new DefaultListModel<>();
        advertiserList = new JList<>(listModel);
        advertiserList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof ShowAdvertisers) {
            populateData(((ShowAdvertisers) arg).list);
        } else if (arg instanceof ShowAdvertiserAds) {
            ShowAdvertiserAds showAds = (ShowAdvertiserAds) arg;
            showAds(showAds.advertiserName, showAds.list);
        }
    }

    private void populateData(List<AdvertiserTransfer> list) {
        this.listModel.clear();
        this.advertiserData = list;
        for (AdvertiserTransfer tr : list) {
            this.listModel.addElement(tr.toString());
        }
    }

    private void showAds(String forAdvertiser, List<AdTransfer> list) {
        if (list.isEmpty()) {
            show("This advertiser has no ads");
            return;
        }

        List<String> names = list.stream().map(AdTransfer::toString).collect(Collectors.toList());
        AdvertisetAdsDialog dialog = new AdvertisetAdsDialog(String.format("Ads for %s", forAdvertiser), names);
        dialog.pack();
        dialog.willShow();
        dialog.setVisible(true);
    }

    @Override
    public JPanel getPanelHandler() {
        return (JPanel) $$$getRootComponent$$$();
    }

    @Override
    public void willShow() {
        this.controller.getAllAdvertisers();
    }
}
