package radio.ui;

import javax.swing.*;
import java.awt.*;

public class EventListPanel implements ApplicationWindow {
    private JPanel background;
    private JList eventPanel;
    private JButton newEventButton;
    private JButton searchButton;
    private JTextField textField1;
    private JPanel searchPanel;
    private JScrollPane listPanel;

    EventListPanel(MainController _cont) {
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        background = new JPanel();
        background.setLayout(new BorderLayout(0, 0));
        listPanel = new JScrollPane();
        background.add(listPanel, BorderLayout.CENTER);
        eventPanel = new JList();
        listPanel.setViewportView(eventPanel);
        newEventButton = new JButton();
        newEventButton.setText("+ Nuevo");
        background.add(newEventButton, BorderLayout.SOUTH);
        searchPanel = new JPanel();
        searchPanel.setLayout(new BorderLayout(0, 0));
        background.add(searchPanel, BorderLayout.NORTH);
        searchButton = new JButton();
        searchButton.setText("Go");
        searchPanel.add(searchButton, BorderLayout.EAST);
        textField1 = new JTextField();
        searchPanel.add(textField1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return background;
    }

    @Override
    public JPanel getPanelHandler() {
        return (JPanel) $$$getRootComponent$$$();
    }
}
