package radio.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

import radio.ui.MainWindow.Panels;

public class LandingWindow implements ApplicationWindow {
    private JPanel background;

    private JButton tematicaButton;
    private JButton incidenciasButton;
    private JButton anunciantesButton;
    private JButton agendaMusicalButton;
    private JButton playlistsButton;
    private JButton archivoMusicalButton;
    private JButton planificacionButton;
    private JButton logOutButton;

    LandingWindow(MainController controller) {
        $$$setupUI$$$();
        tematicaButton.addActionListener(_e -> controller.swapWindow(Panels.THEMES));
        incidenciasButton.addActionListener(_e -> controller.swapWindow(Panels.TICKETS));
        anunciantesButton.addActionListener(_e -> controller.swapWindow(Panels.ADVERTISERS));
        agendaMusicalButton.addActionListener(_e -> controller.swapWindow(Panels.EVENTS));
        playlistsButton.addActionListener(_e -> controller.swapWindow(Panels.PLAYLISTS));
        archivoMusicalButton.addActionListener(_e -> controller.swapWindow(Panels.MUSIC_ARCHIVE));
        planificacionButton.addActionListener(_e -> controller.swapWindow(Panels.PLANNING));
        logOutButton.addActionListener(_e -> controller.logout());
    }

    @Override
    public JPanel getPanelHandler() {
        return (JPanel) this.$$$getRootComponent$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        background = new JPanel();
        background.setLayout(new GridLayoutManager(8, 1, new Insets(0, 0, 0, 0), -1, -1));
        tematicaButton = new JButton();
        tematicaButton.setText("Temática");
        tematicaButton.setToolTipText("Show Selected Subsystem");
        background.add(tematicaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        incidenciasButton = new JButton();
        incidenciasButton.setText("Incidencias");
        background.add(incidenciasButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        anunciantesButton = new JButton();
        anunciantesButton.setText("Anunciantes");
        background.add(anunciantesButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        agendaMusicalButton = new JButton();
        agendaMusicalButton.setText("Agenda Musical");
        background.add(agendaMusicalButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        playlistsButton = new JButton();
        playlistsButton.setText("Playlists");
        background.add(playlistsButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        archivoMusicalButton = new JButton();
        archivoMusicalButton.setText("Archivo Musical");
        background.add(archivoMusicalButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        planificacionButton = new JButton();
        planificacionButton.setText("Planificación");
        background.add(planificacionButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logOutButton = new JButton();
        logOutButton.setText("Log Out");
        background.add(logOutButton, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return background;
    }

}
